In [5]:
import pandas as pd

In [6]:
game_sales_dataframe = pd.read_csv('vgchartz-2024.csv')

In [7]:
game_sales_dataframe.info()

<class 'pandas.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   img           64016 non-null  str
 1   title         64016 non-null  str
 2   console       64016 non-null  str
 3   genre         64016 non-null  str
 4   publisher     64016 non-null  str
 5   developer     63999 non-null  str
 6   critic_score  6678 non-null   float64
 7   total_sales   18922 non-null  float64
 8   na_sales      12637 non-null  float64
 9   jp_sales      6726 non-null   float64
 10  pal_sales     12824 non-null  float64
 11  other_sales   15128 non-null  float64
 12  release_date  56965 non-null  str
 13  last_update   17879 non-null  str
dtypes: float64(6), str(8)
memory usage: 6.8 MB

In [8]:
game_sales_dataframe.head()

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,9.4,20.32,6.37,0.99,9.85,3.12,2013-09-17,NaN
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,9.7,19.39,6.06,0.60,9.71,3.02,2014-11-18,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,9.6,16.15,8.41,0.47,5.49,1.78,2002-10-28,NaN
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,NaN,15.86,9.06,0.06,5.33,1.42,2013-09-17,NaN
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,8.1,15.09,6.18,0.41,6.05,2.44,2015-11-06,2018-01-14

In [9]:
game_sales_dataframe.sample(5)

,img,title,console,genre,publisher,developer,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales,release_date,last_update
39157,/games/boxart/full_yamasa-digi-selection_880Ja...,Yamasa Digi Selection,PS,Misc,Yamasa Entertainment,Yamasa Entertainment,NaN,NaN,NaN,NaN,NaN,NaN,2002-04-25,NaN
14947,/games/boxart/full_8879401AmericaFrontccc.jpg,Sea Park Tycoon,DS,Simulation,Destineer,Most Wanted Entertainment,NaN,0.03,0.02,NaN,0.01,0.0,2010-04-13,NaN
14471,/games/boxart/full_8856433PALFrontccc.jpg,Death Mark,NS,Adventure,Aksys Games,Experience Inc.,NaN,0.03,0.02,0.00,NaN,0.0,2018-10-31,2019-03-17
45724,/games/boxart/5394136ccc.jpg,Diddy Kong Racing,N64,Racing,Nintendo,Rare Ltd.,8.3,NaN,NaN,NaN,NaN,NaN,1997-11-24,NaN
12639,/games/boxart/full_8250885JapanFrontccc.jpg,Kamiwaza,PS2,Action,Acquire,Acquire,NaN,0.05,NaN,0.05,NaN,NaN,2006-08-31,NaN

In [10]:
game_sales_dataframe.isnull().sum()

img                 0
title               0
console             0
genre               0
publisher           0
developer          17
critic_score    57338
total_sales     45094
na_sales        51379
jp_sales        57290
pal_sales       51192
other_sales     48888
release_date     7051
last_update     46137
dtype: int64

In [11]:
game_sales_dataframe.describe()

,critic_score,total_sales,na_sales,jp_sales,pal_sales,other_sales
count,6678.000000,18922.000000,12637.000000,6726.000000,12824.000000,15128.000000
mean,7.220440,0.349113,0.264740,0.102281,0.149472,0.043041
std,1.457066,0.807462,0.494787,0.168811,0.392653,0.126643
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,6.400000,0.030000,0.050000,0.020000,0.010000,0.000000
50%,7.500000,0.120000,0.120000,0.040000,0.040000,0.010000
75%,8.300000,0.340000,0.280000,0.120000,0.140000,0.030000
max,10.000000,20.320000,9.760000,2.130000,9.850000,3.120000

In [12]:
game_sales_dataframe.nunique()

img             56177
title           39798
console            81
genre              20
publisher        3383
developer        8862
critic_score       89
total_sales       482
na_sales          320
jp_sales          121
pal_sales         256
other_sales       133
release_date     7922
last_update      1545
dtype: int64

In [21]:
#Now, calculating the percentaje of nulls by column

In [20]:
(game_sales_dataframe.isnull().sum() / len(game_sales_dataframe) * 100).sort_values(ascending=False)

critic_score    89.568233
jp_sales        89.493252
na_sales        80.259623
pal_sales       79.967508
other_sales     76.368408
last_update     72.071045
total_sales     70.441765
release_date    11.014434
developer        0.026556
publisher        0.000000
img              0.000000
genre            0.000000
console          0.000000
title            0.000000
dtype: float64

In [22]:
game_sales_dataframe["critic_score"]

0        9.4
1        9.7
2        9.6
3        NaN
4        8.1
        ...
64011    NaN
64012    NaN
64013    NaN
64014    NaN
64015    NaN
Name: critic_score, Length: 64016, dtype: float64