In [1]:
import pandas as pd

In [5]:
g_s_df = pd.read_csv('vgchartz_enriched.csv')

In [6]:
g_s_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   img                      64016 non-null  str
 1   title                    64016 non-null  str
 2   console                  64016 non-null  str
 3   genre                    64016 non-null  str
 4   publisher                64016 non-null  str
 5   developer                63999 non-null  str
 6   has_critic_score         64016 non-null  bool
 7   critic_score             6678 non-null   float64
 8   has_total_sales_record   64016 non-null  bool
 9   total_sales              18922 non-null  float64
 10  has_na_sales_record      64016 non-null  bool
 11  na_sales                 12637 non-null  float64
 12  has_jp_sales_record      64016 non-null  bool
 13  jp_sales                 6726 non-null   float64
 14  has_pal_sales_record     64016 non-null  bool
 15  pal_sales                12824 non-null  float64
 16  has_other_sales_record   64016 non-null  bool
 17  other_sales              15128 non-null  float64
 18  has_release_date_record  64016 non-null  bool
 19  release_date             56965 non-null  str
 20  has_last_update_record   64016 non-null  bool
 21  last_update              17879 non-null  str
dtypes: bool(8), float64(6), str(8)
memory usage: 7.3 MB

In [8]:
#changing some data types
g_s_df["release_date"] = pd.to_datetime(g_s_df["release_date"])

In [9]:
g_s_df["last_update"] = pd.to_datetime(g_s_df["last_update"])

In [10]:
g_s_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 64016 entries, 0 to 64015
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   img                      64016 non-null  str
 1   title                    64016 non-null  str
 2   console                  64016 non-null  str
 3   genre                    64016 non-null  str
 4   publisher                64016 non-null  str
 5   developer                63999 non-null  str
 6   has_critic_score         64016 non-null  bool
 7   critic_score             6678 non-null   float64
 8   has_total_sales_record   64016 non-null  bool
 9   total_sales              18922 non-null  float64
 10  has_na_sales_record      64016 non-null  bool
 11  na_sales                 12637 non-null  float64
 12  has_jp_sales_record      64016 non-null  bool
 13  jp_sales                 6726 non-null   float64
 14  has_pal_sales_record     64016 non-null  bool
 15  pal_sales                12824 non-null  float64
 16  has_other_sales_record   64016 non-null  bool
 17  other_sales              15128 non-null  float64
 18  has_release_date_record  64016 non-null  bool
 19  release_date             56965 non-null  datetime64[us]
 20  has_last_update_record   64016 non-null  bool
 21  last_update              17879 non-null  datetime64[us]
dtypes: bool(8), datetime64[us](2), float64(6), str(6)
memory usage: 7.3 MB

In [15]:
#checking duplicateds records
g_s_df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...
64011    False
64012    False
64013    False
64014    False
64015    False
Length: 64016, dtype: bool

In [16]:
g_s_df.duplicated().sum()

np.int64(0)

In [18]:
#checking duplicated titles
g_s_df["title"].duplicated().sum()

np.int64(24218)

In [20]:
title_duplicates_mask = g_s_df["title"].duplicated(keep=False)

In [21]:
g_s_df[title_duplicates_mask]

,img,title,console,genre,publisher,developer,has_critic_score,critic_score,has_total_sales_record,total_sales,...,has_jp_sales_record,jp_sales,has_pal_sales_record,pal_sales,has_other_sales_record,other_sales,has_release_date_record,release_date,has_last_update_record,last_update
0,/games/boxart/full_6510540AmericaFrontccc.jpg,Grand Theft Auto V,PS3,Action,Rockstar Games,Rockstar North,True,9.4,True,20.32,...,True,0.99,True,9.85,True,3.12,True,2013-09-17,False,NaT
1,/games/boxart/full_5563178AmericaFrontccc.jpg,Grand Theft Auto V,PS4,Action,Rockstar Games,Rockstar North,True,9.7,True,19.39,...,True,0.60,True,9.71,True,3.02,True,2014-11-18,True,2018-01-03
2,/games/boxart/827563ccc.jpg,Grand Theft Auto: Vice City,PS2,Action,Rockstar Games,Rockstar North,True,9.6,True,16.15,...,True,0.47,True,5.49,True,1.78,True,2002-10-28,False,NaT
3,/games/boxart/full_9218923AmericaFrontccc.jpg,Grand Theft Auto V,X360,Action,Rockstar Games,Rockstar North,False,NaN,True,15.86,...,True,0.06,True,5.33,True,1.42,True,2013-09-17,False,NaT
4,/games/boxart/full_4990510AmericaFrontccc.jpg,Call of Duty: Black Ops 3,PS4,Shooter,Activision,Treyarch,True,8.1,True,15.09,...,True,0.41,True,6.05,True,2.44,True,2015-11-06,True,2018-01-14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
64009,/games/boxart/full_2129671JapanFrontccc.jpg,World End Syndrome,PSV,Visual Novel,Arc System Works,Arc System Works,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2018-04-26,True,2019-04-03
64010,/games/boxart/full_2294305JapanFrontccc.jpg,World End Syndrome,PS4,Visual Novel,Arc System Works,Arc System Works,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2018-04-26,True,2019-04-03
64011,/games/boxart/full_2779838AmericaFrontccc.jpg,XBlaze Lost: Memories,PC,Visual Novel,Aksys Games,Arc System Works,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2016-08-11,True,2019-01-28
64012,/games/boxart/full_8031506AmericaFrontccc.jpg,"Yoru, Tomosu",PS4,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2020-07-30,True,2020-05-09
64013,/games/boxart/full_6553045AmericaFrontccc.jpg,"Yoru, Tomosu",NS,Visual Novel,Nippon Ichi Software,Nippon Ichi Software,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2020-07-30,True,2020-05-09

In [22]:
g_s_df[title_duplicates_mask].sort_values("title")

,img,title,console,genre,publisher,developer,has_critic_score,critic_score,has_total_sales_record,total_sales,...,has_jp_sales_record,jp_sales,has_pal_sales_record,pal_sales,has_other_sales_record,other_sales,has_release_date_record,release_date,has_last_update_record,last_update
47263,/games/boxart/full_6946124AmericaFrontccc.jpg,#DRIVE Rally,PS4,Racing,Unknown,Pixel Perfect Dude,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2023-11-10
47264,/games/boxart/full_7569449AmericaFrontccc.jpg,#DRIVE Rally,PS5,Racing,Unknown,Pixel Perfect Dude,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2023-11-10
47265,/games/boxart/full_9093834AmericaFrontccc.jpg,#DRIVE Rally,XOne,Racing,Unknown,Pixel Perfect Dude,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2023-11-10
47268,/games/boxart/full_8870515AmericaFrontccc.jpg,#DRIVE Rally,PC,Racing,Unknown,Pixel Perfect Dude,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2023-11-10
47266,/games/boxart/full_9079529AmericaFrontccc.jpg,#DRIVE Rally,XS,Racing,Unknown,Pixel Perfect Dude,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2023-11-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15498,/games/boxart/full_1817338AmericaFrontccc.jpg,uDraw Studio: Instant Artist,X360,Misc,THQ,THQ,False,NaN,True,0.02,...,False,NaN,True,0.01,True,0.00,True,2011-11-15,True,2019-05-09
18330,/games/boxart/default.jpg,uDraw Studio: Instant Artist,PS3,Misc,THQ,Unknown,False,NaN,True,0.00,...,False,NaN,True,0.00,True,0.00,True,2011-11-15,False,NaT
7741,/games/boxart/full_2106119AmericaFrontccc.png,uDraw Studio: Instant Artist,Wii,Misc,THQ,THQ,False,NaN,True,0.17,...,False,NaN,True,0.09,True,0.02,True,2011-11-15,False,NaT
28955,/games/boxart/default.jpg,way to the woods,PC,Adventure,Unknown,Unknown,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2019-06-09
28954,/games/boxart/default.jpg,way to the woods,XOne,Adventure,Unknown,Unknown,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,False,NaT,True,2019-06-09

In [31]:
title_console_duplicates_mask = g_s_df[["title", "console", "developer","publisher"]].duplicated(keep=False)

In [32]:
g_s_df[title_console_duplicates_mask].sort_values("title")

,img,title,console,genre,publisher,developer,has_critic_score,critic_score,has_total_sales_record,total_sales,...,has_jp_sales_record,jp_sales,has_pal_sales_record,pal_sales,has_other_sales_record,other_sales,has_release_date_record,release_date,has_last_update_record,last_update
18885,/games/boxart/full_6533178JapanFrontccc.jpg,Aokana: Four Rhythm Across the Blue,NS,Visual Novel,Sprite,Sprite,False,NaN,True,0.00,...,True,0.00,False,NaN,False,NaN,True,2020-08-21,True,2018-04-07
63793,/games/boxart/full_3273209AmericaFrontccc.jpg,Aokana: Four Rhythm Across the Blue,PSV,Visual Novel,Sprite,Sprite,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2016-02-25,True,2020-05-11
63794,/games/boxart/full_8608130AmericaFrontccc.jpg,Aokana: Four Rhythm Across the Blue,NS,Visual Novel,Sprite,Sprite,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2020-08-21,True,2020-05-11
14271,/games/boxart/full_838274JapanFrontccc.jpg,Aokana: Four Rhythm Across the Blue,PS4,Visual Novel,Sprite,Sprite,False,NaN,True,0.03,...,True,0.03,False,NaN,False,NaN,True,2020-08-21,True,2018-04-07
13118,/games/boxart/full_6793274JapanFrontccc.jpg,Aokana: Four Rhythm Across the Blue,PSV,Visual Novel,Sprite,Sprite,False,NaN,True,0.05,...,True,0.05,False,NaN,False,NaN,True,2016-02-25,True,2018-04-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63266,/games/boxart/full_9636671AmericaFrontccc.jpg,Z,PC,Strategy,Virgin Interactive,Bitmap Brothers,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,1996-07-31,False,NaT
2439,/games/boxart/full_2726763JapanFrontccc.jpg,Zaidan Houjin Nippon Kanji Nouryoku Kentei Kyo...,DS,Misc,IE Institute,IE Institute,False,NaN,True,0.66,...,True,0.66,False,NaN,False,NaN,True,2006-11-09,False,NaT
2438,/games/boxart/full_4455632JapanFrontccc.jpg,Zaidan Houjin Nippon Kanji Nouryoku Kentei Kyo...,DS,Misc,IE Institute,IE Institute,False,NaN,True,0.66,...,True,0.66,False,NaN,False,NaN,True,2006-11-09,False,NaT
43231,/games/boxart/full_8161397JapanFrontccc.jpg,bit Generations: Soundvoyager,GBA,Puzzle,Nintendo,skip Ltd.,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2006-07-27,False,NaT
43232,/games/boxart/6510255ccc.jpg,bit Generations: Soundvoyager,GBA,Puzzle,Nintendo,skip Ltd.,False,NaN,False,NaN,...,False,NaN,False,NaN,False,NaN,True,2006-07-27,False,NaT

In [33]:
#Although there are repeated title + console combinations, the associated records differ in other attributes (e.g. developer, publisher, image, sales or critic score). Therefore, these records were preserved pending further domain validation.

In [34]:
g_s_df.to_csv("vgchartz_cleaned.csv", index=False)